### ISSUE TITLE
resume session

### ISSUE THREAD

**Issue by thomasspiesser** [boundsj/ObjectiveDDP#107]
I'm trying to resume a session after the app was closed/background. Is there a session token or something similar to access or save on the device to reconnect?

**Comment by flashfabrixx** [comment]
@mikey0000 Finally had the time to check out your changes which somehow aren't downloaded via ```pod update```. But in general your fix works as expected. There is just a small bug because the changed ```logonWithSessionToken``` method isn't implemented in [here](https://github.com/boundsj/ObjectiveDDP/blob/0527209627a2a290ad148bd6c95174d7707a9189/ObjectiveDDP/MeteorClient.m#L280) yet.

**Comment by mikey0000** [comment]
Oops nice catch, must have been tired, either you can submit a pull request or I'll get on it later tonight.

**Comment by Bijiabo** [comment]
Can there have a callback func for logonWithSessionToken?

**Comment by mikey0000** [comment]
There is.

**Comment by gsaslis** [comment]
@mikey0000 with regards to the callback func (mentioned by @Bijiabo above).. did you mean there is one in Swift, or in Objective-C ?

If I can understand the bridge code correctly (which is not that probable since I hardly know any Objective-C syntax), the callback seems to be missing in 0.1.8? 

is there a newer version?

**Comment by mikey0000** [comment]
none of the codebase is in swift, you should get auto completion for the method in xcode in your swift code. run off master instead of the version. I've been meaning to bump the version, ill try to do that today

**Comment by gsaslis** [comment]
Yes, you're right!! setting up the podfile to pick up the github version, instead of 0.1.8, worked for me ; )

:+1: 




Thanks a lot for the prompt reply!!!



—
Yorgos Saslis

**Comment by mikey0000** [comment]
no problems mate! I'll get a new version out today.
