### ISSUE TITLE
Use facebook to login to meteor

### ISSUE THREAD

**Issue by vephinx** [boundsj/ObjectiveDDP#122]
Would it be possible for users to login using the facebook service, with help of the facebook SDK?

**Comment by vephinx** [comment]
Thanks. It is possible to signup, using the following code:
```swift
var someDict:NSDictionary = [
    "credentialToken": "...",
    "credentialSecret": "..."]

var myDict:NSDictionary = ["oauth" : someDict, "username": "some_username"]
println(myDict)
self.meteorData.meteorClient.signupWithUserParameters(myDict, responseCallback: {(response, error) -> Void in
    if((error) != nil) {
        println(error)
        return
    }
    self.handleSuccessfulAuth()
})
```

To login, using the following code (however gives an error):

```swift
var someDict:NSDictionary = [
    "credentialToken": "..." ,
    "credentialSecret": "..."]

var myDict:NSDictionary = ["oauth" : someDict]
println(myDict)

meteorData.meteorClient.logonWithUserParameters(myDict, responseCallback: {(response, error) -> Void in
    if((error) != nil) {
        println(error)
        return
    }
    self.handleSuccessfulAuth()
})
```

With the login code, I receive the following error: 

    No matching login attempt found [145546287]

It could be that I am using the wrong credentialToken or/and credentialSecret. 

```swift 
"credentialToken":  FBSession.activeSession().accessTokenData.accessToken,
"credentialSecret": //application secret
```

However, in [accounts-oauth.js](https://github.com/meteor/meteor/blob/e742697675b734d021277b333ababa9151f52b8e/packages/accounts-oauth/oauth_client.js#L71) in meteor, the credentialSecret is retrieved as follows:
```js
var credentialSecret = OAuth._retrieveCredentialSecret(credentialToken)
```

So I think the credentialSecret can be retrieved from the credentialToken, and has nothing to do with the application secret.

**Comment by mikey0000** [comment]
I'll see if I can find some time to look into this, good progress so far anyway.

**Comment by jasper-lu** [comment]
I've been digging through the meteor source, and it seems like from the end of the OAuth popup [here](https://github.com/meteor/meteor/blob/master/packages/oauth/end_of_popup_response.html), the code makes a handleCredentialSecret call, which stores the oauth secret in a dictionary with the token as key.

Then, the credential secret is retrieved from the dictionary with the following call in [accounts-oauth.js](https://github.com/meteor/meteor/blob/e742697675b734d021277b333ababa9151f52b8e/packages/accounts-oauth/oauth_client.js#L71):

    var credentialSecret = OAuth._retrieveCredentialSecret(credentialToken)

Is there a way to retrieve the secret from the end of the oauth popup in mobile?

**Comment by mikey0000** [comment]
I would need to start or play with a project trying to do this to really help you. I don't have time to set one up just yet, if you are willing to provide a project I can work off to help you solve this I'll be able to make head way into this. There must be a way.

**Comment by jasper-lu** [comment]
I haven't started work on a flow for this just yet, but I can send over
back end code for it once I start working on login code for my app.

**Comment by jasper-lu** [comment]
@vephinx 

I've been tracing through the meteor code some more.

So it seems like the _retrieveCredentialSecret call fetches an object from the OAuth._pendingCredentials collection with a key equal to the token and a secret equal to the app secret or null.

Then, it retrieves the pending credentials using oauth's version of loginHandler:

    var result = OAuth.retrieveCredential(options.oauth.credentialToken,
                                        options.oauth.credentialSecret);

And the user is logged in.

        var result = runLoginHandlers(self, options);
        return attemptLogin(self, "login", arguments, result);

From what I understand, it seems like the magic code putting everything together is in [oauth/oauth_server.js](https://github.com/meteor/meteor/blob/8e2b5612a9d1c4d745dbf7a3bded43a27cc6fd2e/packages/oauth/oauth_server.js):

    // Listen to incoming OAuth http requests
    WebApp.connectHandlers.use(function(req, res, next) {
        // Need to create a Fiber since we're using synchronous http calls and nothing
        // else is wrapping this in a fiber automatically
        Fiber(function () {
            middleware(req, res, next);
        }).run();
    });

    var middleware = function (req, res, next) {
        /* before code */
        OAuth._storePendingCredential(OAuth._credentialTokenFromQuery(req.query), err);
        /* after code */
    }

This code explains why the error 

    No matching login attempt found [145546287]

pops up. There's literally no matching login attempt in the pendingCredentials connection. I'm not sure if this means that there is no login attempt sent at all, though (the secret could just as easily be stored as null on the server).

However, after switching credentialSecret to null, I'm getting Match Failed errors. Unfortunately, I can't trace the errors since nothing shows up on my server, so I guess this is as far as I go tonight.

@vephinx, how did you get the Match failed errors to log on your server?

**Comment by vephinx** [comment]
@jasper-lu, I originally got the Match Failed errors because I was parsing the credentialToken and credentialSecret incorrectly. 

Originally:

```swift
 var myArrayOfDict: NSArray = [
        ["credentialToken": credentialToken],
        ["credentialSecret": credentialSecret]
    ]
    var myDict:NSDictionary = ["oauth" : myArrayOfDict, "username": "some_username"]
```
This responds with Match Failed. Instead, one should be using NSDictionary inside NSDictionary, as follows (eg. to signup):

``` swift
var someDict:NSDictionary = [
    "credentialToken": "...",
    "credentialSecret": "..."]

var myDict:NSDictionary = ["oauth" : someDict, "username": "some_username"]
```

It is actually possible to signup this way using any arbitrary credentialToken and credentialSecret this way.

**Comment by jasper-lu** [comment]
@Vephinx,

I thought you were still getting a "no matching login attempt" error on login?

Also, I'm getting a match failed error when I replace credential secret with null, instead of my own app secret, although the server side code runs something like check(options.credentialSecret, String || null)

**Comment by jasper-lu** [comment]
Update: the credentialtoken wasn't ending up on the server because no http call was being made to the server with the access token.

Looking through it further, my guess now is that when the Facebook api sends the access token back to the client through http, the server also catches the access token and stores it on its own server for verification later.

Unless there's a way to spoof a url while authorizing Facebook, I'm not sure how to proceed here other than through writing a package with a modified version of Meteor's own oauth system.

I'm going to look into the former solution a bit more.

**Comment by jasper-lu** [comment]
I cracked it and implemented loginwithOauth for the android ddp client starting from [line 365](https://github.com/jasper-lu/android-ddp-client/blob/master/src/com/keysolutions/ddpclient/android/DDPStateSingleton.java).

I've been working on an objective c version in my free time and should be done testing it by wednesday.

However, I'm not sure how good of an idea it would be to pull it into the main repo, since mobile OAuth login will only be supported through custom accounts-x packages, at least until/if meteor changes some of the base code.

**Comment by mikey0000** [comment]
Nice work! Have you opened an issue on the meteor github about this?

**Comment by jasper-lu** [comment]
I've sent in a pull request with my version of the package, so I'm guessing there's no need to make the issue

**Comment by mikey0000** [comment]
Ahh cool I'll subscribe to your pull request so I can see what happens there. Feel free to submit a pull request enabling Oauth in objectiveDDP I won't merge until there is mainstream support though.

**Comment by jasper-lu** [comment]
@vephinx  if you still need it, you can check out the code here: https://github.com/boundsj/ObjectiveDDP/pull/124

**Comment by vephinx** [comment]
@jasper-lu Thanks so much! :+1:
