### ISSUE TITLE
React Native Bridge?

### ISSUE THREAD

**Issue by fardeemmunir** [boundsj/ObjectiveDDP#132]
I checked out React Native and damnnn, it was awesome. So obviously the question now is to how to integrate it with Meteor. I was hoping Node DDP would work but websockets support for react native is not available. So any idea how to bridge Objective DDP to React native? I guess it would be easy since most of the hard word has already been done( :+1: for that ).

**Comment by mikey0000** [comment]
Well Javascript is a first class citizen in iOS and OSX now so you could just import it and use it in js land. I can't say it would work as you need to have your initialisation in the appDelegate and since I haven't used react native I really can't help. Now I know they've actually released it publicly.
