### ISSUE TITLE
cannot get any data using subscription with parameters

### ISSUE THREAD

**Issue by anderson916** [boundsj/ObjectiveDDP#137]
Hi there,

I have the following server code:

```javascript
Meteor.publish('simpleCompartments', function(serial) {
       return Compartments.find({serial: serial}, {sort: {createdAt: -1}, limit: 5});
});
```
I cannot get any data using the following swift code:
```swift
Meteor.addSubscription("simpleCompartments", withParameters: ["serial"])
```

Is it supported?  Thanks.

**Comment by anderson916** [comment]
I can receive "simpleCompartments_ready" notification, but no other notification about the collections.

**Comment by mikey0000** [comment]
Are you sure your parameter and function (server side)  returns anything? Yes the library supports swift, can you take questions and asks for help to gitter instead of the issues please, that way others can help you as well. 

On May 8, 2015 8:33:46 PM GMT+12:00, John Zhang <notifications@github.com> wrote:
>I can receive "simpleCompartments_ready" notification, but no other
>notification about the collections.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/137#issuecomment-100152631

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
